/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  VRFConsumerBase,
  VRFConsumerBaseInterface,
} from "../../../../../@chainlink/contracts/src/v0.8/VRFConsumerBase";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "randomness",
        type: "uint256",
      },
    ],
    name: "rawFulfillRandomness",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class VRFConsumerBase__factory {
  static readonly abi = _abi;
  static createInterface(): VRFConsumerBaseInterface {
    return new Interface(_abi) as VRFConsumerBaseInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): VRFConsumerBase {
    return new Contract(address, _abi, runner) as unknown as VRFConsumerBase;
  }
}
